eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: zuul
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG-SERVER
      name: application-plat
      profile: dev
server:
  port: 4000

zuul:
  ignoredServices: '*'  # 忽略所有
  routes:
    plat:
      path: /plat/**  # 平台服务的请求路径
      serviceId: plat-server
  prefix: /service # 请求前缀